version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: html-conversion-api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm run dev
    restart: unless-stopped 